name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y cmake libcmocka-dev gdb

      - name: Log Installed Libraries
        run: dpkg -l | grep cmocka

      - name: Build
        run: |
          make V=1

      - name: Run Tests with Core Dumps
        run: |
          sudo sysctl -w kernel.core_pattern=core_dumps/core.%e.%p
          ulimit -c unlimited
          ./tests/build/tests/run || gdb ./tests/build/tests/run core_dumps/core* -ex "bt" -ex "quit"
