name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y cmake libcmocka-dev
      - name: make
        run: make
